version: '3.5'
services:
  openapi:
    build: .
    ports:
      - 8080:8080
    volumes:
      - ./spec:/usr/share/nginx/html/spec
    environment:
      URLS: "[
        { url: '/spec/dns.yaml', name: 'DNS' },
        { url: '/spec/mail.yaml', name: 'Mail'},
        { url: '/spec/paas.yaml', name: 'PaaS' },
        { url: '/spec/dbaas.yaml', name: 'DBaaS' },
        { url: '/spec/object-storage.yaml', name: 'Object Storage' },
        { url: '/spec/file-browser.yaml', name: 'File Browser' },
        { url: '/spec/database-inspector.yaml', name: 'Database Inspector' },
        { url: '/spec/Iaas.yaml', name: 'Iaas' },
        { url: '/spec/ai-chat-completions.yaml', name: 'AI - Chat Completions' },
        { url: '/spec/ai-tts.yaml', name: 'AI - TTS' },
        { url: '/spec/ai-stt.yaml', name: 'AI - STT' },
        { url: '/spec/ai-image-generation.yaml', name: 'AI - Image Generation' },
        { url: '/spec/ai-embeddings.yaml', name: 'AI - Embeddings' },
        { url: '/spec/ai-workspaces.yaml', name: 'AI - Workspaces' },
        { url: '/spec/ai-keys.yaml', name: 'AI - API Keys' },
        { url: '/spec/ai-models.yaml', name: 'AI - Models' },
        { url: '/spec/ai-logs.yaml', name: 'AI - Logs' },
        { url: '/spec/ai-playground.yaml', name: 'AI - Playground' },
        ]"
